### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PSYCHO1512** [Terpz710/BankNotesPlus#2]
PocketMine-MP Crash Dump Mon Dec 9 06:49:12 UTC 2024

PocketMine-MP version: 5.23.1 [Protocol 766]
Git commit: 2b0daebc2a72784d6ea1744d6b0b91e7ab66baba
PHP version: 8.2.25
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BankNotesPlus

Thread: Main
Error: Call to undefined method Terpz710\BankNotesPlus\Economy\EconomyManager::reduceMoney()
File: plugins/BankNotesPlus_dev-32.phar/src/Terpz710/BankNotesPlus/Command/BNCommand
Line: 41
Type: Error
Backtrace:
#0 pmsrc/src/command/SimpleCommandMap(218): Terpz710\BankNotesPlus\Command\BNCommand->execute(object pocketmine\player\Player#207301, string[8] banknote, array[1])
#1 pmsrc/src/Server(1466): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#207301, string[10] banknote 1)
#2 pmsrc/src/player/Player(1560): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#207301, string[10] banknote 1)
#3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(826): pocketmine\player\Player->chat(string[11] /banknote 1)
#4 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#113189)
#5 pmsrc/src/network/mcpe/NetworkSession(472): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#155312)
#6 pmsrc/src/network/mcpe/NetworkSession(410): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#113189, string[33] M./banknote 1.)E....o..-....o...T)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[35] .!M./banknote 1.)E....o..-....o...T)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[44] .s.41..._T.Y..)..$....d6^......Cf...T.....7.)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#193347)
#10 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#12 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#14 pmsrc/src/Server(1733): pocketmine\snooze\SleeperHandler->sleepUntil(float 1733726952.9967)
#15 pmsrc/src/Server(1097): pocketmine\Server->tickProcessor()
#16 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#17 pmsrc/src/PocketMine(378): pocketmine\server()
#18 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMP9dYMy5.tar/src/PocketMine.php)

Code:
[32]     public function execute(CommandSender $sender, string $commandLabel, array $args) {
[33]         if (!$this->testPermission($sender)) {
[34]             return true;
[35]         }
[36] 
[37]         if ($sender instanceof Player) {
[38]             if (count($args) === 1 && is_numeric($args[0]) && $args[0] > 0) {
[39]                 $amount = (int)$args[0];
[40] 
[41]                 $this->economyManager->reduceMoney($sender, $amount, function($success) use ($sender, $amount) {
[42]                     if ($success) {
[43]                         $this->plugin->convertToBankNote($sender, $amount);
[44]                         $message = $this->plugin->getConfig()->get("convert_success_message");
[45]                         $message = str_replace("{amount}", (string)$amount, $message);
[46]                         $sender->sendMessage($message);
[47]                     } else {
[48]                         $message = $this->plugin->getConfig()->get("convert_failure_message");
[49]                         $sender->sendMessage($message);
[50]                     }
[51]                 });

**Comment by PSYCHO1512** [comment]
Used both the dev and latest release version

**Comment by Terpz710** [comment]
@PSYCHO1512 Ive fixed it use v1.0.4 thank you for bringing this to my attention.

https://poggit.pmmp.io/ci/Terpz710/BankNotesPlus/BankNotesPlus
